### ISSUE TITLE
uninitialized constant Mongo::MongoClient

### ISSUE THREAD

**Issue by ptrikutam** [stripe/mosql#112]
I recently updated to `mongoid 5.0`, which in turn relies on `mongo (~> 2.1)`. Unfortunately, we're getting this error right now:

```
/app/vendor/bundle/ruby/2.1.0/gems/mosql-0.4.0/lib/mosql/cli.rb:115:in `connect_mongo': uninitialized constant Mongo::MongoClient (NameError)
	from /app/vendor/bundle/ruby/2.1.0/gems/mosql-0.4.0/lib/mosql/cli.rb:149:in `run'
	from /app/vendor/bundle/ruby/2.1.0/gems/mosql-0.4.0/lib/mosql/cli.rb:16:in `run'
	from /app/vendor/bundle/ruby/2.1.0/gems/mosql-0.4.0/bin/mosql:5:in `<top (required)>'
```

I presume there are a lot of other API related errors like this as well.

I realize this is because the officially supported `mongo` version for `mosql` is 1.x, but are there any ideas of how to get around this short of rolling back the `mongo` version? 

Any idea on time frame to update to the latest mongo driver?

**Comment by ptrikutam** [comment]
Oh, and let me just re-iterate -- thank you for all your great work with mosql! This is a fantastic project and very very useful. Thanks!

**Comment by dmitrypol** [comment]
+1

**Comment by abhishekalai** [comment]
Can the guys @stripe/mosql please add a list of dependencies to their README. It might help to solve a lot of errors.
