### ISSUE TITLE
NoMethod Error

### ISSUE THREAD

**Issue by akinokaze** [stripe/mosql#99]
Getting a NoMethod error on initial run. Any ideas?

`mosql -c /etc/mosql/collections.yml --mongo mongodb://ip/test --sql postgres://host/test`

`/usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/schema.rb:83:in 'block (2 levels) in create_schema': undefined method '[]' for nil:NilClass (NoMethodError)
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/schema.rb:80:in 'each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/schema.rb:80:in 'block in create_schema'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/schema.rb:79:in 'each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/schema.rb:79:in 'create_schema'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/streamer.rb:90:in 'initial_import'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/streamer.rb:28:in 'import'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/cli.rb:167:in 'run'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/lib/mosql/cli.rb:16:in 'run'
    from /usr/local/lib/ruby/gems/2.0.0/gems/mosql-0.4.3/bin/mosql:5:in '<top (required)>'
    from /usr/local/bin/mosql:23:in 'load'
    from /usr/local/bin/mosql:23:in '<main>'`

**Comment by mayatskiy** [comment]
+1

**Comment by tbatchelli** [comment]
I had this issue and it was caused by missing meta-table, e.g.:

```yaml
staging-bookings:
  bookings:
    :meta:
      :table: bookings
    :columns:
      ...
```

the documentation is not clear in that this is needed, or there is a bug somewhere, but adding this metadata made it all work.

**Comment by joanrodriguez** [comment]
This did the trick for me, documentation unclear indeed

**Comment by GMolini** [comment]
That did the trick for me too. Thanks!
